apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sol9-redis-prod
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: sol9
    environment: prod
spec:
  project: sol9
  source:
    repoURL: https://github.com/Ahmed-Shehzad/Sol9
    targetRevision: HEAD
    path: K8s/helm/redis
    helm:
      releaseName: sol9
      values: |
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: sol9-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
