apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sol9-apps-prod
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: sol9
spec:
  project: sol9
  source:
    repoURL: https://github.com/Ahmed-Shehzad/Sol9_K8s
    targetRevision: HEAD
    path: apps/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
